#+TITLE: Articulated Body Pose Tracking
#+latex_header: \usepackage[citestyle=authoryear-icomp,bibstyle=authoryear, hyperref=true,backref=true,maxcitenames=3,url=true,backend=biber,natbib=true] {biblatex}
#+latex_header: \addbibresource{literature.bib}

* State of the art
[@xiao_simple_2018]
** Benchmarks
*** MPII Benchmark 
http://human-pose.mpi-inf.mpg.de
425 Gb
*** Posetrack
https://posetrack.net
**** 2017
33.5 Gb
**** 2018
81.8 Gb
*** C(ommon) O(bjects in) Co(ntext)
http://cocodataset.org
* Current problems
  
* Open Questions
- Do we need non-linear dynamics?
  If inducing-point and -value are given compute
  Jacobian and apply contraction theory:
  dynamics are contracting if absolute values of eigenvectors of the
  jacobian are all smaller than one.
  - Compare LDS with GPDM

* Ideas
- Use SVAE to extend vCGPDM
- Use constrained biomechanical model:
  Animators often control dofs to simulate physics,
  this should not be done by the CNS. 
- Build pose tracker working on natural *and* point-light display
- Do pose estimation on klt-tracked (or similar) features
- Vitruvian Man: Fit biomechanical skeleton into image by learning
  the transform matrix. Connection to hierarchy detection
  [@tenenbaum]

* Literature
** @johnson_composing_2016
Graphical model with neural-network based observation-likelihoods
- @khan_conjugate-computation_2017:
  Generalizes to arbitrary conjugacy structure and removes need to run 
  conjugate part until convergence
- @linderman_recurrent_2016:
  This model has nonlinear transition/emission models
** @lin_variational_2018
Generalize and simplify SVAE [github: vmp-for-svae]
